### ISSUE TITLE
WiFi not visible to mobile device

### ISSUE THREAD

**Issue by rimwulf** [spacehuhn/WiFiDuck#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your problem

Wifi visible to computer & iPhone but not to my Android device (2

### Steps to reproduce

The two devices in question is a Samsung Galaxy S22 stock and Moto g power (2020 model)
Things I did:
Formatted Wi-Fi duck
Changed Wi-Fi channel
Changed SSID
Pulled out and we inserted still didn't detect.
Even used Wigle WiFi but it still didn't detect.

### What hardware are you using?

Samsung Galaxy S22 stock, Moto g power (2020) bootloader unlocked, iPhone 6s, Xmobile tablet

**Comment by Devsider** [comment]
I'm experiencing a similar issue, however the phone shows the wifi but is unable to connect. My windows pc connects without any problems.
