### ISSUE TITLE
[Locale]: IT

### ISSUE THREAD

**Issue by spicyynugget** [spacehuhn/WiFiDuck#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What layout are you translating?

IT

### Where do you need help?

Basically all capital "Y" gets replaced with letter "Z". I've made sure to include "LOCALE IT" at the top of the script but it doesn't seems to solve the issue. for example che command "STRING reg /add "HKEY...."  outputs "HKEZ"

**Comment by spacehuhn** [comment]
Hi. Can you post an image of your keyboard and a full script example that doesn't work as intended?

**Comment by spicyynugget** [comment]
Yes sure, I'll try to be more specific.

I'm using a DSTIKE WiFI Duck

this is my keyboard 

![IMG_6309](https://github.com/SpacehuhnTech/WiFiDuck/assets/133059370/fc9c14ee-e6a1-485e-ad4d-994775c45c76)

to give an example of a script i wrote this test script:

LOCALE IT
DEFAULTDELAY 1000

GUI r
DELAY 200

STRING notepad
ENTER

DELAY 700

STRING this is a test, YYY yyy


following the output:


![image](https://github.com/SpacehuhnTech/WiFiDuck/assets/133059370/f9cb0d7c-3a86-4a02-a8b0-c92f68a30e0d)


I've tested this on different systems and  made sure to use the correct layout in windows setting

![image](https://github.com/SpacehuhnTech/WiFiDuck/assets/133059370/417e05d5-97f3-42ad-afcc-46178b804c35)

Thanks in advance for the help! really love this project <3

**Comment by spacehuhn** [comment]
Hi. I finally had some time to look into it, and I believe this is an issue with version 1.1.0. Try updating your device to 1.2.0

It's important that you update both chips. The process can be a bit tedious, I admit, but you can find the necessary instructions on wifiduck.com: https://wifiduck.com/docs/category/software-installation

**Comment by spicyynugget** [comment]
I'm going to retry to update after the last failed attempts, thanks again!
