### ISSUE TITLE
[Feature Request]: Support ESP32-S2

### ISSUE THREAD

**Issue by spuder** [spacehuhn/WiFiDuck#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem

It would be nice to support more microcontrollers such as the new line of ESP32-S2/ ESP32-S3 boards as they support keyboard emulation. 

### Solution

The wemos S2 Mini supports keyboard emulation

https://www.wemos.cc/en/latest/s2/s2_mini.html

Others have gotten it working in esphome

https://github.com/esphome/esphome/pull/3917

**Comment by eadmaster** [comment]
have you checked this?
https://github.com/wasdwasd0105/SuperWiFiDuck

**Comment by spuder** [comment]
Thats exactly what I'm looking for. Just got it working on a Wemos S2. Thank you
