### ISSUE TITLE
[Feature] Change Device type

### ISSUE THREAD

**Issue by jLynx** [spacehuhn/WiFiDuck#14]
It would be awesome to add the functionality to be able to change the device type/PID live without needing to re program it with arduino studio.

I have a few ideas on how this can be done.
- It may be possible to do it directly in code which would be the easiest way to do it
- Have a way to flash flash the device (Like an OTA which you are currently working on) but being able to select the type you want there (Appley keyboard, Microsoft keyboard, etc...). Then it will just reflash with the ID you want

**Comment by spacehuhn** [comment]
So this is possible now due to the custom Arduino board package.
As far as I know, this can't be changed dynamically though, you'll need to recompile the code.

**Comment by jLynx** [comment]
But you know how to can flash it on the Web interface, can you flash it with a new device id?

**Comment by spacehuhn** [comment]
The Atmega can't be flashed OTA :(

**Comment by jLynx** [comment]
😢
