### ISSUE TITLE
[Bug] SSID (and password) won't save

### ISSUE THREAD

**Issue by jLynx** [spacehuhn/WiFiDuck#18]
SSID, password and channel won't save. 

This I think is either 2 thing. It's not saving the eeprom or the front end is not passing it through correctly. I'll investigate and push a fix through

**Comment by spacehuhn** [comment]
I was thinking of refactoring the settings to use the SPIFFS too but eh idk the EEPROM is super easy to use and can't be fucked up as easily.

**Comment by jLynx** [comment]
Yeah no need to do that. I'll fix it in 30 min

**Comment by jLynx** [comment]
Found the fix. will push through soon

**Comment by jLynx** [comment]
Fixed in https://github.com/spacehuhn/WiFiDuck/pull/20

**Comment by jLynx** [comment]
Merged

**Comment by GrandJohnny** [comment]
how can i fix this problem?

**Comment by Bommlon** [comment]
update to the latest version
