### ISSUE TITLE
I just flashed both boards and set the wires up, but now whenever I try to create a ducky script it won't run it. I type the basic "Hello World", but it wouldn't even let me run the program. I don't know if my boards just aren't communicating or it is software. Both boards are read individually from the system, idk anything whould help greatly.  (The error message is, "Internal Connection Error")

### ISSUE THREAD

**Issue by AlexM05** [spacehuhn/WiFiDuck#32]
**Describe the error**
A clear and concise description of what the problem is.
What do you think causes it?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Version [e.g. 1.0]
 - Hardware [e.g. DSTIKE, DIY]

**Attempts**
What have you already tried and didn't work out.

**Additional context**
Provide as much information as possible, better too much than too little!
If you don't use this template, your issue might be closed and tagged invalid!

**Comment by jLynx** [comment]
Please dont create a spammy title. Please put the details in the issue itself and dont leave the informaion required for us to help blank. This will be closed until you have fixed these issues I have just stated
