### ISSUE TITLE
[Question] What if the PC has an AV effect?

### ISSUE THREAD

**Issue by Mr-xn** [spacehuhn/WiFiDuck#4]

**Comment by spacehuhn** [comment]
Can you please elaborate on your question.

**Comment by Mr-xn** [comment]
> Can you please elaborate on your question.

thanks your reply.
bro,i just want to know:
If the anti-virus software is installed on the PC, can it still work normally? 
Or is there any way to bypass this?

**Comment by spacehuhn** [comment]
Depends on the anti virus software and how it reacts.  
If it blocks any unknown USB device, you first need to confirm that it's harmless.

**Comment by davedarko** [comment]
Sir, no anti-virus helps against deauthing. The deauther is the perfect wi-fi jammer, bro.

**Comment by Mr-xn** [comment]
OK . Thanks
