### ISSUE TITLE
Error setting up the ESP8266 [Help] 

### ISSUE THREAD

**Issue by ChebiMora** [spacehuhn/WiFiDuck#7]
When I upload the code "esp_duck.ino" from the Arduino IDE I get an error
I have installed all the libaries installed including the one for ESP8266 (Im using the NodeMCU)

I open de folder and left it as it was and tried to upload it but it gave me the error

Here is the copy of the error : 
(some parts are in spanish but i think they are not very imprtant)

Arduino:1.8.10 (Windows 10), Tarjeta:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 4M (3M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

El Sketch usa 413040 bytes (39%) del espacio de almacenamiento de programa. El máximo es 1044464 bytes.
Las variables Globales usan 32104 bytes (39%) de la memoria dinámica, dejando 49816 bytes para las variables locales. El máximo es 81920 bytes.
esptool.py v2.6
2.6
esptool.py v2.6
Serial port COM6
Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):
  File "C:\Users\j_mor\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2/tools/upload.py", line 25, in <module>
    esptool.main(fakeargs)
  File "C:/Users/j_mor/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 2653, in main
    esp.connect(args.before)
  File "C:/Users/j_mor/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 468, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

I m using the Arduino IDE

**Comment by spacehuhn** [comment]
This is a connection error.
Check you have the drivers installed, a working USB cable (with data!) and the correct COM port selected.
